site_name: ChaProEV
nav:
 - Home: index.md
 - How to use: using.md
 - Files: 
 - Dataframes/pandas:
 - 
 - Plotting:
            - Math: math.md
            - Physics: physics.md

theme: readthedocs