name: Github CI
on: [push]
jobs:

  Publish_documentation:
    runs-on: windows-latest
    steps:
      - run: pip install mkdocs
      - run: mkdocs gh-deploy

    # Testing:
    # runs-on: windows-latest
    # steps:
      # - run: pip install pytest
      # - run: pytest /tests