name: Github CI
on: [push]
jobs:

  Publish_documentation:
    runs-on: windows-latest
    env:
      CONFIG_FILE: folder/mkdocs.yml
    steps:
      - run: pip install mkdocs
      - working-directory: ./docs
        run: mkdocs gh-deploy

    # Testing:
    # runs-on: windows-latest
    # steps:
      # - run: pip install pytest
      # - run: pytest /tests